// tbclient.GetLevelInfo.GetLevelInfoReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: GetLevelInfoReqIdl.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLevelInfoReqIdl struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          *GetLevelInfoReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelInfoReqIdl) Reset() {
	*x = GetLevelInfoReqIdl{}
	mi := &file_GetLevelInfoReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelInfoReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelInfoReqIdl) ProtoMessage() {}

func (x *GetLevelInfoReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetLevelInfoReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelInfoReqIdl.ProtoReflect.Descriptor instead.
func (*GetLevelInfoReqIdl) Descriptor() ([]byte, []int) {
	return file_GetLevelInfoReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetLevelInfoReqIdl) GetData() *GetLevelInfoReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLevelInfoReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *protobuf.CommonReq    `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	ForumId       int64                  `protobuf:"varint,1,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelInfoReqIdl_DataReq) Reset() {
	*x = GetLevelInfoReqIdl_DataReq{}
	mi := &file_GetLevelInfoReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelInfoReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelInfoReqIdl_DataReq) ProtoMessage() {}

func (x *GetLevelInfoReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetLevelInfoReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelInfoReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*GetLevelInfoReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_GetLevelInfoReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetLevelInfoReqIdl_DataReq) GetCommon() *protobuf.CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetLevelInfoReqIdl_DataReq) GetForumId() int64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

var File_GetLevelInfoReqIdl_proto protoreflect.FileDescriptor

const file_GetLevelInfoReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x18GetLevelInfoReqIdl.proto\x1a\x0fCommonReq.proto\"\x8f\x01\n" +
	"\x12GetLevelInfoReqIdl\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.GetLevelInfoReqIdl.DataReqR\x04data\x1aH\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18\x02 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x19\n" +
	"\bforum_id\x18\x01 \x01(\x03R\aforumIdb\x06proto3"

var (
	file_GetLevelInfoReqIdl_proto_rawDescOnce sync.Once
	file_GetLevelInfoReqIdl_proto_rawDescData []byte
)

func file_GetLevelInfoReqIdl_proto_rawDescGZIP() []byte {
	file_GetLevelInfoReqIdl_proto_rawDescOnce.Do(func() {
		file_GetLevelInfoReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetLevelInfoReqIdl_proto_rawDesc), len(file_GetLevelInfoReqIdl_proto_rawDesc)))
	})
	return file_GetLevelInfoReqIdl_proto_rawDescData
}

var file_GetLevelInfoReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetLevelInfoReqIdl_proto_goTypes = []any{
	(*GetLevelInfoReqIdl)(nil),         // 0: GetLevelInfoReqIdl
	(*GetLevelInfoReqIdl_DataReq)(nil), // 1: GetLevelInfoReqIdl.DataReq
	(*protobuf.CommonReq)(nil),         // 2: CommonReq
}
var file_GetLevelInfoReqIdl_proto_depIdxs = []int32{
	1, // 0: GetLevelInfoReqIdl.data:type_name -> GetLevelInfoReqIdl.DataReq
	2, // 1: GetLevelInfoReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetLevelInfoReqIdl_proto_init() }
func file_GetLevelInfoReqIdl_proto_init() {
	if File_GetLevelInfoReqIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetLevelInfoReqIdl_proto_rawDesc), len(file_GetLevelInfoReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetLevelInfoReqIdl_proto_goTypes,
		DependencyIndexes: file_GetLevelInfoReqIdl_proto_depIdxs,
		MessageInfos:      file_GetLevelInfoReqIdl_proto_msgTypes,
	}.Build()
	File_GetLevelInfoReqIdl_proto = out.File
	file_GetLevelInfoReqIdl_proto_goTypes = nil
	file_GetLevelInfoReqIdl_proto_depIdxs = nil
}
