// tbclient.GetLevelInfo.GetLevelInfoResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: GetLevelInfoResIdl.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLevelInfoResIdl struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Error         *protobuf.Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          *GetLevelInfoResIdl_DataRes `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelInfoResIdl) Reset() {
	*x = GetLevelInfoResIdl{}
	mi := &file_GetLevelInfoResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelInfoResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelInfoResIdl) ProtoMessage() {}

func (x *GetLevelInfoResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_GetLevelInfoResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelInfoResIdl.ProtoReflect.Descriptor instead.
func (*GetLevelInfoResIdl) Descriptor() ([]byte, []int) {
	return file_GetLevelInfoResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *GetLevelInfoResIdl) GetError() *protobuf.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetLevelInfoResIdl) GetData() *GetLevelInfoResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLevelInfoResIdl_DataRes struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	IsLike int32                  `protobuf:"varint,2,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"`
	// repeated LevelInfo level_info = 1;
	LevelName     string `protobuf:"bytes,4,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`
	UserLevel     int32  `protobuf:"varint,3,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelInfoResIdl_DataRes) Reset() {
	*x = GetLevelInfoResIdl_DataRes{}
	mi := &file_GetLevelInfoResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelInfoResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelInfoResIdl_DataRes) ProtoMessage() {}

func (x *GetLevelInfoResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_GetLevelInfoResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelInfoResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*GetLevelInfoResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_GetLevelInfoResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetLevelInfoResIdl_DataRes) GetIsLike() int32 {
	if x != nil {
		return x.IsLike
	}
	return 0
}

func (x *GetLevelInfoResIdl_DataRes) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *GetLevelInfoResIdl_DataRes) GetUserLevel() int32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

var File_GetLevelInfoResIdl_proto protoreflect.FileDescriptor

const file_GetLevelInfoResIdl_proto_rawDesc = "" +
	"\n" +
	"\x18GetLevelInfoResIdl.proto\x1a\vError.proto\"\xc5\x01\n" +
	"\x12GetLevelInfoResIdl\x12\x1c\n" +
	"\x05error\x18\x02 \x01(\v2\x06.ErrorR\x05error\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.GetLevelInfoResIdl.DataResR\x04data\x1a`\n" +
	"\aDataRes\x12\x17\n" +
	"\ais_like\x18\x02 \x01(\x05R\x06isLike\x12\x1d\n" +
	"\n" +
	"level_name\x18\x04 \x01(\tR\tlevelName\x12\x1d\n" +
	"\n" +
	"user_level\x18\x03 \x01(\x05R\tuserLevelb\x06proto3"

var (
	file_GetLevelInfoResIdl_proto_rawDescOnce sync.Once
	file_GetLevelInfoResIdl_proto_rawDescData []byte
)

func file_GetLevelInfoResIdl_proto_rawDescGZIP() []byte {
	file_GetLevelInfoResIdl_proto_rawDescOnce.Do(func() {
		file_GetLevelInfoResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetLevelInfoResIdl_proto_rawDesc), len(file_GetLevelInfoResIdl_proto_rawDesc)))
	})
	return file_GetLevelInfoResIdl_proto_rawDescData
}

var file_GetLevelInfoResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetLevelInfoResIdl_proto_goTypes = []any{
	(*GetLevelInfoResIdl)(nil),         // 0: GetLevelInfoResIdl
	(*GetLevelInfoResIdl_DataRes)(nil), // 1: GetLevelInfoResIdl.DataRes
	(*protobuf.Error)(nil),             // 2: Error
}
var file_GetLevelInfoResIdl_proto_depIdxs = []int32{
	2, // 0: GetLevelInfoResIdl.error:type_name -> Error
	1, // 1: GetLevelInfoResIdl.data:type_name -> GetLevelInfoResIdl.DataRes
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetLevelInfoResIdl_proto_init() }
func file_GetLevelInfoResIdl_proto_init() {
	if File_GetLevelInfoResIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetLevelInfoResIdl_proto_rawDesc), len(file_GetLevelInfoResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetLevelInfoResIdl_proto_goTypes,
		DependencyIndexes: file_GetLevelInfoResIdl_proto_depIdxs,
		MessageInfos:      file_GetLevelInfoResIdl_proto_msgTypes,
	}.Build()
	File_GetLevelInfoResIdl_proto = out.File
	file_GetLevelInfoResIdl_proto_goTypes = nil
	file_GetLevelInfoResIdl_proto_depIdxs = nil
}
