// tbclient.AddPoll.AddPollResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: AddPollResIdl.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPollResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *protobuf.Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPollResIdl) Reset() {
	*x = AddPollResIdl{}
	mi := &file_AddPollResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPollResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPollResIdl) ProtoMessage() {}

func (x *AddPollResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_AddPollResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPollResIdl.ProtoReflect.Descriptor instead.
func (*AddPollResIdl) Descriptor() ([]byte, []int) {
	return file_AddPollResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *AddPollResIdl) GetError() *protobuf.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_AddPollResIdl_proto protoreflect.FileDescriptor

const file_AddPollResIdl_proto_rawDesc = "" +
	"\n" +
	"\x13AddPollResIdl.proto\x1a\vError.proto\"-\n" +
	"\rAddPollResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05errorb\x06proto3"

var (
	file_AddPollResIdl_proto_rawDescOnce sync.Once
	file_AddPollResIdl_proto_rawDescData []byte
)

func file_AddPollResIdl_proto_rawDescGZIP() []byte {
	file_AddPollResIdl_proto_rawDescOnce.Do(func() {
		file_AddPollResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddPollResIdl_proto_rawDesc), len(file_AddPollResIdl_proto_rawDesc)))
	})
	return file_AddPollResIdl_proto_rawDescData
}

var file_AddPollResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AddPollResIdl_proto_goTypes = []any{
	(*AddPollResIdl)(nil),  // 0: AddPollResIdl
	(*protobuf.Error)(nil), // 1: Error
}
var file_AddPollResIdl_proto_depIdxs = []int32{
	1, // 0: AddPollResIdl.error:type_name -> Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AddPollResIdl_proto_init() }
func file_AddPollResIdl_proto_init() {
	if File_AddPollResIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddPollResIdl_proto_rawDesc), len(file_AddPollResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddPollResIdl_proto_goTypes,
		DependencyIndexes: file_AddPollResIdl_proto_depIdxs,
		MessageInfos:      file_AddPollResIdl_proto_msgTypes,
	}.Build()
	File_AddPollResIdl_proto = out.File
	file_AddPollResIdl_proto_goTypes = nil
	file_AddPollResIdl_proto_depIdxs = nil
}
