// tbclient.AddPoll.AddPollReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: AddPollReqIdl.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPollReqIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AddPollReqIdl_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPollReqIdl) Reset() {
	*x = AddPollReqIdl{}
	mi := &file_AddPollReqIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPollReqIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPollReqIdl) ProtoMessage() {}

func (x *AddPollReqIdl) ProtoReflect() protoreflect.Message {
	mi := &file_AddPollReqIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPollReqIdl.ProtoReflect.Descriptor instead.
func (*AddPollReqIdl) Descriptor() ([]byte, []int) {
	return file_AddPollReqIdl_proto_rawDescGZIP(), []int{0}
}

func (x *AddPollReqIdl) GetData() *AddPollReqIdl_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddPollReqIdl_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      uint64                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Options       string                 `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Common        *protobuf.CommonReq    `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	ForumId       uint64                 `protobuf:"varint,4,opt,name=forum_id,json=forumId,proto3" json:"forum_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPollReqIdl_DataReq) Reset() {
	*x = AddPollReqIdl_DataReq{}
	mi := &file_AddPollReqIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPollReqIdl_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPollReqIdl_DataReq) ProtoMessage() {}

func (x *AddPollReqIdl_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_AddPollReqIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPollReqIdl_DataReq.ProtoReflect.Descriptor instead.
func (*AddPollReqIdl_DataReq) Descriptor() ([]byte, []int) {
	return file_AddPollReqIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddPollReqIdl_DataReq) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *AddPollReqIdl_DataReq) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *AddPollReqIdl_DataReq) GetCommon() *protobuf.CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *AddPollReqIdl_DataReq) GetForumId() uint64 {
	if x != nil {
		return x.ForumId
	}
	return 0
}

var File_AddPollReqIdl_proto protoreflect.FileDescriptor

const file_AddPollReqIdl_proto_rawDesc = "" +
	"\n" +
	"\x13AddPollReqIdl.proto\x1a\x0fCommonReq.proto\"\xbc\x01\n" +
	"\rAddPollReqIdl\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.AddPollReqIdl.DataReqR\x04data\x1a\x7f\n" +
	"\aDataReq\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\x04R\bthreadId\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\tR\aoptions\x12\"\n" +
	"\x06common\x18\x03 \x01(\v2\n" +
	".CommonReqR\x06common\x12\x19\n" +
	"\bforum_id\x18\x04 \x01(\x04R\aforumIdb\x06proto3"

var (
	file_AddPollReqIdl_proto_rawDescOnce sync.Once
	file_AddPollReqIdl_proto_rawDescData []byte
)

func file_AddPollReqIdl_proto_rawDescGZIP() []byte {
	file_AddPollReqIdl_proto_rawDescOnce.Do(func() {
		file_AddPollReqIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddPollReqIdl_proto_rawDesc), len(file_AddPollReqIdl_proto_rawDesc)))
	})
	return file_AddPollReqIdl_proto_rawDescData
}

var file_AddPollReqIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AddPollReqIdl_proto_goTypes = []any{
	(*AddPollReqIdl)(nil),         // 0: AddPollReqIdl
	(*AddPollReqIdl_DataReq)(nil), // 1: AddPollReqIdl.DataReq
	(*protobuf.CommonReq)(nil),    // 2: CommonReq
}
var file_AddPollReqIdl_proto_depIdxs = []int32{
	1, // 0: AddPollReqIdl.data:type_name -> AddPollReqIdl.DataReq
	2, // 1: AddPollReqIdl.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AddPollReqIdl_proto_init() }
func file_AddPollReqIdl_proto_init() {
	if File_AddPollReqIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddPollReqIdl_proto_rawDesc), len(file_AddPollReqIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddPollReqIdl_proto_goTypes,
		DependencyIndexes: file_AddPollReqIdl_proto_depIdxs,
		MessageInfos:      file_AddPollReqIdl_proto_msgTypes,
	}.Build()
	File_AddPollReqIdl_proto = out.File
	file_AddPollReqIdl_proto_goTypes = nil
	file_AddPollReqIdl_proto_depIdxs = nil
}
