// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: Lcm.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Common struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cuid          string                 `protobuf:"bytes,1,opt,name=cuid,proto3" json:"cuid,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Manufacture   string                 `protobuf:"bytes,4,opt,name=manufacture,proto3" json:"manufacture,omitempty"`
	ModelType     string                 `protobuf:"bytes,5,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	AppId         string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppVersion    string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,8,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Network       string                 `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	RomVersion    string                 `protobuf:"bytes,10,opt,name=rom_version,json=romVersion,proto3" json:"rom_version,omitempty"`
	UserKey       string                 `protobuf:"bytes,11,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Common) Reset() {
	*x = Common{}
	mi := &file_Lcm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Common) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Common) ProtoMessage() {}

func (x *Common) ProtoReflect() protoreflect.Message {
	mi := &file_Lcm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Common.ProtoReflect.Descriptor instead.
func (*Common) Descriptor() ([]byte, []int) {
	return file_Lcm_proto_rawDescGZIP(), []int{0}
}

func (x *Common) GetCuid() string {
	if x != nil {
		return x.Cuid
	}
	return ""
}

func (x *Common) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Common) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Common) GetManufacture() string {
	if x != nil {
		return x.Manufacture
	}
	return ""
}

func (x *Common) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *Common) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Common) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Common) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Common) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Common) GetRomVersion() string {
	if x != nil {
		return x.RomVersion
	}
	return ""
}

func (x *Common) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type LcmNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Action        int32                  `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LcmNotify) Reset() {
	*x = LcmNotify{}
	mi := &file_Lcm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcmNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcmNotify) ProtoMessage() {}

func (x *LcmNotify) ProtoReflect() protoreflect.Message {
	mi := &file_Lcm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcmNotify.ProtoReflect.Descriptor instead.
func (*LcmNotify) Descriptor() ([]byte, []int) {
	return file_Lcm_proto_rawDescGZIP(), []int{1}
}

func (x *LcmNotify) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *LcmNotify) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type LcmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Common        *Common                `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        int32                  `protobuf:"varint,5,opt,name=action,proto3" json:"action,omitempty"`
	StartType     int32                  `protobuf:"varint,6,opt,name=start_type,json=startType,proto3" json:"start_type,omitempty"`
	ConnType      int32                  `protobuf:"varint,7,opt,name=conn_type,json=connType,proto3" json:"conn_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LcmRequest) Reset() {
	*x = LcmRequest{}
	mi := &file_Lcm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcmRequest) ProtoMessage() {}

func (x *LcmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Lcm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcmRequest.ProtoReflect.Descriptor instead.
func (*LcmRequest) Descriptor() ([]byte, []int) {
	return file_Lcm_proto_rawDescGZIP(), []int{2}
}

func (x *LcmRequest) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *LcmRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LcmRequest) GetCommon() *Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *LcmRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LcmRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *LcmRequest) GetStartType() int32 {
	if x != nil {
		return x.StartType
	}
	return 0
}

func (x *LcmRequest) GetConnType() int32 {
	if x != nil {
		return x.ConnType
	}
	return 0
}

type LcmResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LogId          int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ErrorCode      int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	NextIntervalMs int64                  `protobuf:"varint,4,opt,name=next_interval_ms,json=nextIntervalMs,proto3" json:"next_interval_ms,omitempty"`
	ServerInfo     string                 `protobuf:"bytes,5,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LcmResponse) Reset() {
	*x = LcmResponse{}
	mi := &file_Lcm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcmResponse) ProtoMessage() {}

func (x *LcmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Lcm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcmResponse.ProtoReflect.Descriptor instead.
func (*LcmResponse) Descriptor() ([]byte, []int) {
	return file_Lcm_proto_rawDescGZIP(), []int{3}
}

func (x *LcmResponse) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *LcmResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *LcmResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *LcmResponse) GetNextIntervalMs() int64 {
	if x != nil {
		return x.NextIntervalMs
	}
	return 0
}

func (x *LcmResponse) GetServerInfo() string {
	if x != nil {
		return x.ServerInfo
	}
	return ""
}

type RpcData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LcmRequest    *LcmRequest            `protobuf:"bytes,1,opt,name=lcm_request,json=lcmRequest,proto3" json:"lcm_request,omitempty"`
	LcmResponse   *LcmResponse           `protobuf:"bytes,2,opt,name=lcm_response,json=lcmResponse,proto3" json:"lcm_response,omitempty"`
	LcmNotify     *LcmNotify             `protobuf:"bytes,3,opt,name=lcm_notify,json=lcmNotify,proto3" json:"lcm_notify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcData) Reset() {
	*x = RpcData{}
	mi := &file_Lcm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcData) ProtoMessage() {}

func (x *RpcData) ProtoReflect() protoreflect.Message {
	mi := &file_Lcm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcData.ProtoReflect.Descriptor instead.
func (*RpcData) Descriptor() ([]byte, []int) {
	return file_Lcm_proto_rawDescGZIP(), []int{4}
}

func (x *RpcData) GetLcmRequest() *LcmRequest {
	if x != nil {
		return x.LcmRequest
	}
	return nil
}

func (x *RpcData) GetLcmResponse() *LcmResponse {
	if x != nil {
		return x.LcmResponse
	}
	return nil
}

func (x *RpcData) GetLcmNotify() *LcmNotify {
	if x != nil {
		return x.LcmNotify
	}
	return nil
}

var File_Lcm_proto protoreflect.FileDescriptor

const file_Lcm_proto_rawDesc = "" +
	"\n" +
	"\tLcm.proto\"\xc3\x02\n" +
	"\x06Common\x12\x12\n" +
	"\x04cuid\x18\x01 \x01(\tR\x04cuid\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12 \n" +
	"\vmanufacture\x18\x04 \x01(\tR\vmanufacture\x12\x1d\n" +
	"\n" +
	"model_type\x18\x05 \x01(\tR\tmodelType\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\x12\x1f\n" +
	"\vsdk_version\x18\b \x01(\tR\n" +
	"sdkVersion\x12\x18\n" +
	"\anetwork\x18\t \x01(\tR\anetwork\x12\x1f\n" +
	"\vrom_version\x18\n" +
	" \x01(\tR\n" +
	"romVersion\x12\x19\n" +
	"\buser_key\x18\v \x01(\tR\auserKey\":\n" +
	"\tLcmNotify\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\"\xcc\x01\n" +
	"\n" +
	"LcmRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\x06common\x18\x03 \x01(\v2\a.CommonR\x06common\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06action\x18\x05 \x01(\x05R\x06action\x12\x1d\n" +
	"\n" +
	"start_type\x18\x06 \x01(\x05R\tstartType\x12\x1b\n" +
	"\tconn_type\x18\a \x01(\x05R\bconnType\"\xab\x01\n" +
	"\vLcmResponse\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12(\n" +
	"\x10next_interval_ms\x18\x04 \x01(\x03R\x0enextIntervalMs\x12\x1f\n" +
	"\vserver_info\x18\x05 \x01(\tR\n" +
	"serverInfo\"\x93\x01\n" +
	"\aRpcData\x12,\n" +
	"\vlcm_request\x18\x01 \x01(\v2\v.LcmRequestR\n" +
	"lcmRequest\x12/\n" +
	"\flcm_response\x18\x02 \x01(\v2\f.LcmResponseR\vlcmResponse\x12)\n" +
	"\n" +
	"lcm_notify\x18\x03 \x01(\v2\n" +
	".LcmNotifyR\tlcmNotifyb\x06proto3"

var (
	file_Lcm_proto_rawDescOnce sync.Once
	file_Lcm_proto_rawDescData []byte
)

func file_Lcm_proto_rawDescGZIP() []byte {
	file_Lcm_proto_rawDescOnce.Do(func() {
		file_Lcm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Lcm_proto_rawDesc), len(file_Lcm_proto_rawDesc)))
	})
	return file_Lcm_proto_rawDescData
}

var file_Lcm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Lcm_proto_goTypes = []any{
	(*Common)(nil),      // 0: Common
	(*LcmNotify)(nil),   // 1: LcmNotify
	(*LcmRequest)(nil),  // 2: LcmRequest
	(*LcmResponse)(nil), // 3: LcmResponse
	(*RpcData)(nil),     // 4: RpcData
}
var file_Lcm_proto_depIdxs = []int32{
	0, // 0: LcmRequest.common:type_name -> Common
	2, // 1: RpcData.lcm_request:type_name -> LcmRequest
	3, // 2: RpcData.lcm_response:type_name -> LcmResponse
	1, // 3: RpcData.lcm_notify:type_name -> LcmNotify
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Lcm_proto_init() }
func file_Lcm_proto_init() {
	if File_Lcm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Lcm_proto_rawDesc), len(file_Lcm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Lcm_proto_goTypes,
		DependencyIndexes: file_Lcm_proto_depIdxs,
		MessageInfos:      file_Lcm_proto_msgTypes,
	}.Build()
	File_Lcm_proto = out.File
	file_Lcm_proto_goTypes = nil
	file_Lcm_proto_depIdxs = nil
}
