// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: Rpc.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      int64                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ChunkId       int64                  `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_Rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkInfo) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *ChunkInfo) GetChunkId() int64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

type EventTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTimestamp) Reset() {
	*x = EventTimestamp{}
	mi := &file_Rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTimestamp) ProtoMessage() {}

func (x *EventTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTimestamp.ProtoReflect.Descriptor instead.
func (*EventTimestamp) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{1}
}

func (x *EventTimestamp) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EventTimestamp) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type RpcNotifyMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId      int64                  `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	LogId         int64                  `protobuf:"varint,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	EventList     []*EventTimestamp      `protobuf:"bytes,4,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcNotifyMeta) Reset() {
	*x = RpcNotifyMeta{}
	mi := &file_Rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcNotifyMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcNotifyMeta) ProtoMessage() {}

func (x *RpcNotifyMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcNotifyMeta.ProtoReflect.Descriptor instead.
func (*RpcNotifyMeta) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcNotifyMeta) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RpcNotifyMeta) GetMethodId() int64 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *RpcNotifyMeta) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *RpcNotifyMeta) GetEventList() []*EventTimestamp {
	if x != nil {
		return x.EventList
	}
	return nil
}

type RpcRequestMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId      int64                  `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	LogId         int64                  `protobuf:"varint,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	NeedCommon    int32                  `protobuf:"varint,4,opt,name=need_common,json=needCommon,proto3" json:"need_common,omitempty"`
	EventList     []*EventTimestamp      `protobuf:"bytes,5,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequestMeta) Reset() {
	*x = RpcRequestMeta{}
	mi := &file_Rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequestMeta) ProtoMessage() {}

func (x *RpcRequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequestMeta.ProtoReflect.Descriptor instead.
func (*RpcRequestMeta) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RpcRequestMeta) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RpcRequestMeta) GetMethodId() int64 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *RpcRequestMeta) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *RpcRequestMeta) GetNeedCommon() int32 {
	if x != nil {
		return x.NeedCommon
	}
	return 0
}

func (x *RpcRequestMeta) GetEventList() []*EventTimestamp {
	if x != nil {
		return x.EventList
	}
	return nil
}

type RpcResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId      int64                  `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	LogId         int64                  `protobuf:"varint,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorText     string                 `protobuf:"bytes,5,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	EventList     []*EventTimestamp      `protobuf:"bytes,6,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponseMeta) Reset() {
	*x = RpcResponseMeta{}
	mi := &file_Rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponseMeta) ProtoMessage() {}

func (x *RpcResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponseMeta.ProtoReflect.Descriptor instead.
func (*RpcResponseMeta) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RpcResponseMeta) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RpcResponseMeta) GetMethodId() int64 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *RpcResponseMeta) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *RpcResponseMeta) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RpcResponseMeta) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

func (x *RpcResponseMeta) GetEventList() []*EventTimestamp {
	if x != nil {
		return x.EventList
	}
	return nil
}

type RpcMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Request            *RpcRequestMeta        `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response           *RpcResponseMeta       `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	CompressType       *int32                 `protobuf:"varint,3,opt,name=compress_type,json=compressType,proto3,oneof" json:"compress_type,omitempty"`
	CorrelationId      int64                  `protobuf:"varint,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AttachmentSize     int32                  `protobuf:"varint,5,opt,name=attachment_size,json=attachmentSize,proto3" json:"attachment_size,omitempty"`
	ChunkInfo          *ChunkInfo             `protobuf:"bytes,6,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	AuthenticationData []byte                 `protobuf:"bytes,7,opt,name=authentication_data,json=authenticationData,proto3" json:"authentication_data,omitempty"`
	Notify             *RpcNotifyMeta         `protobuf:"bytes,8,opt,name=notify,proto3" json:"notify,omitempty"`
	AcceptCompressType int32                  `protobuf:"varint,9,opt,name=accept_compress_type,json=acceptCompressType,proto3" json:"accept_compress_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RpcMeta) Reset() {
	*x = RpcMeta{}
	mi := &file_Rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMeta) ProtoMessage() {}

func (x *RpcMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMeta.ProtoReflect.Descriptor instead.
func (*RpcMeta) Descriptor() ([]byte, []int) {
	return file_Rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RpcMeta) GetRequest() *RpcRequestMeta {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RpcMeta) GetResponse() *RpcResponseMeta {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RpcMeta) GetCompressType() int32 {
	if x != nil && x.CompressType != nil {
		return *x.CompressType
	}
	return 0
}

func (x *RpcMeta) GetCorrelationId() int64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *RpcMeta) GetAttachmentSize() int32 {
	if x != nil {
		return x.AttachmentSize
	}
	return 0
}

func (x *RpcMeta) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *RpcMeta) GetAuthenticationData() []byte {
	if x != nil {
		return x.AuthenticationData
	}
	return nil
}

func (x *RpcMeta) GetNotify() *RpcNotifyMeta {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *RpcMeta) GetAcceptCompressType() int32 {
	if x != nil {
		return x.AcceptCompressType
	}
	return 0
}

var File_Rpc_proto protoreflect.FileDescriptor

const file_Rpc_proto_rawDesc = "" +
	"\n" +
	"\tRpc.proto\"C\n" +
	"\tChunkInfo\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x03R\bstreamId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\x03R\achunkId\"I\n" +
	"\x0eEventTimestamp\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"\x92\x01\n" +
	"\rRpcNotifyMeta\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12\x1b\n" +
	"\tmethod_id\x18\x02 \x01(\x03R\bmethodId\x12\x15\n" +
	"\x06log_id\x18\x03 \x01(\x03R\x05logId\x12.\n" +
	"\n" +
	"event_list\x18\x04 \x03(\v2\x0f.EventTimestampR\teventList\"\xb4\x01\n" +
	"\x0eRpcRequestMeta\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12\x1b\n" +
	"\tmethod_id\x18\x02 \x01(\x03R\bmethodId\x12\x15\n" +
	"\x06log_id\x18\x03 \x01(\x03R\x05logId\x12\x1f\n" +
	"\vneed_common\x18\x04 \x01(\x05R\n" +
	"needCommon\x12.\n" +
	"\n" +
	"event_list\x18\x05 \x03(\v2\x0f.EventTimestampR\teventList\"\xd2\x01\n" +
	"\x0fRpcResponseMeta\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12\x1b\n" +
	"\tmethod_id\x18\x02 \x01(\x03R\bmethodId\x12\x15\n" +
	"\x06log_id\x18\x03 \x01(\x03R\x05logId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_text\x18\x05 \x01(\tR\terrorText\x12.\n" +
	"\n" +
	"event_list\x18\x06 \x03(\v2\x0f.EventTimestampR\teventList\"\xa4\x03\n" +
	"\aRpcMeta\x12)\n" +
	"\arequest\x18\x01 \x01(\v2\x0f.RpcRequestMetaR\arequest\x12,\n" +
	"\bresponse\x18\x02 \x01(\v2\x10.RpcResponseMetaR\bresponse\x12(\n" +
	"\rcompress_type\x18\x03 \x01(\x05H\x00R\fcompressType\x88\x01\x01\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\x03R\rcorrelationId\x12'\n" +
	"\x0fattachment_size\x18\x05 \x01(\x05R\x0eattachmentSize\x12)\n" +
	"\n" +
	"chunk_info\x18\x06 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12/\n" +
	"\x13authentication_data\x18\a \x01(\fR\x12authenticationData\x12&\n" +
	"\x06notify\x18\b \x01(\v2\x0e.RpcNotifyMetaR\x06notify\x120\n" +
	"\x14accept_compress_type\x18\t \x01(\x05R\x12acceptCompressTypeB\x10\n" +
	"\x0e_compress_typeb\x06proto3"

var (
	file_Rpc_proto_rawDescOnce sync.Once
	file_Rpc_proto_rawDescData []byte
)

func file_Rpc_proto_rawDescGZIP() []byte {
	file_Rpc_proto_rawDescOnce.Do(func() {
		file_Rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Rpc_proto_rawDesc), len(file_Rpc_proto_rawDesc)))
	})
	return file_Rpc_proto_rawDescData
}

var file_Rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Rpc_proto_goTypes = []any{
	(*ChunkInfo)(nil),       // 0: ChunkInfo
	(*EventTimestamp)(nil),  // 1: EventTimestamp
	(*RpcNotifyMeta)(nil),   // 2: RpcNotifyMeta
	(*RpcRequestMeta)(nil),  // 3: RpcRequestMeta
	(*RpcResponseMeta)(nil), // 4: RpcResponseMeta
	(*RpcMeta)(nil),         // 5: RpcMeta
}
var file_Rpc_proto_depIdxs = []int32{
	1, // 0: RpcNotifyMeta.event_list:type_name -> EventTimestamp
	1, // 1: RpcRequestMeta.event_list:type_name -> EventTimestamp
	1, // 2: RpcResponseMeta.event_list:type_name -> EventTimestamp
	3, // 3: RpcMeta.request:type_name -> RpcRequestMeta
	4, // 4: RpcMeta.response:type_name -> RpcResponseMeta
	0, // 5: RpcMeta.chunk_info:type_name -> ChunkInfo
	2, // 6: RpcMeta.notify:type_name -> RpcNotifyMeta
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_Rpc_proto_init() }
func file_Rpc_proto_init() {
	if File_Rpc_proto != nil {
		return
	}
	file_Rpc_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Rpc_proto_rawDesc), len(file_Rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Rpc_proto_goTypes,
		DependencyIndexes: file_Rpc_proto_depIdxs,
		MessageInfos:      file_Rpc_proto_msgTypes,
	}.Build()
	File_Rpc_proto = out.File
	file_Rpc_proto_goTypes = nil
	file_Rpc_proto_depIdxs = nil
}
