// tbclient.FrsPage.FrsPageReqIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: FrsPageReqIdl4lp.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrsPageReqIdl4Lp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *FrsPageReqIdl4Lp_DataReq `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageReqIdl4Lp) Reset() {
	*x = FrsPageReqIdl4Lp{}
	mi := &file_FrsPageReqIdl4lp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageReqIdl4Lp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageReqIdl4Lp) ProtoMessage() {}

func (x *FrsPageReqIdl4Lp) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageReqIdl4lp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageReqIdl4Lp.ProtoReflect.Descriptor instead.
func (*FrsPageReqIdl4Lp) Descriptor() ([]byte, []int) {
	return file_FrsPageReqIdl4lp_proto_rawDescGZIP(), []int{0}
}

func (x *FrsPageReqIdl4Lp) GetData() *FrsPageReqIdl4Lp_DataReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type FrsPageReqIdl4Lp_DataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *protobuf.CommonReq    `protobuf:"bytes,39,opt,name=common,proto3" json:"common,omitempty"`
	Kw            string                 `protobuf:"bytes,1,opt,name=kw,proto3" json:"kw,omitempty"`
	Rn            int32                  `protobuf:"varint,2,opt,name=rn,proto3" json:"rn,omitempty"`
	RnNeed        int32                  `protobuf:"varint,3,opt,name=rn_need,json=rnNeed,proto3" json:"rn_need,omitempty"`
	IsGood        int32                  `protobuf:"varint,4,opt,name=is_good,json=isGood,proto3" json:"is_good,omitempty"`
	Cid           int32                  `protobuf:"varint,5,opt,name=cid,proto3" json:"cid,omitempty"`
	Pn            int32                  `protobuf:"varint,15,opt,name=pn,proto3" json:"pn,omitempty"`
	SortType      int32                  `protobuf:"varint,47,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageReqIdl4Lp_DataReq) Reset() {
	*x = FrsPageReqIdl4Lp_DataReq{}
	mi := &file_FrsPageReqIdl4lp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageReqIdl4Lp_DataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageReqIdl4Lp_DataReq) ProtoMessage() {}

func (x *FrsPageReqIdl4Lp_DataReq) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageReqIdl4lp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageReqIdl4Lp_DataReq.ProtoReflect.Descriptor instead.
func (*FrsPageReqIdl4Lp_DataReq) Descriptor() ([]byte, []int) {
	return file_FrsPageReqIdl4lp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FrsPageReqIdl4Lp_DataReq) GetCommon() *protobuf.CommonReq {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *FrsPageReqIdl4Lp_DataReq) GetKw() string {
	if x != nil {
		return x.Kw
	}
	return ""
}

func (x *FrsPageReqIdl4Lp_DataReq) GetRn() int32 {
	if x != nil {
		return x.Rn
	}
	return 0
}

func (x *FrsPageReqIdl4Lp_DataReq) GetRnNeed() int32 {
	if x != nil {
		return x.RnNeed
	}
	return 0
}

func (x *FrsPageReqIdl4Lp_DataReq) GetIsGood() int32 {
	if x != nil {
		return x.IsGood
	}
	return 0
}

func (x *FrsPageReqIdl4Lp_DataReq) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *FrsPageReqIdl4Lp_DataReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *FrsPageReqIdl4Lp_DataReq) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

var File_FrsPageReqIdl4lp_proto protoreflect.FileDescriptor

const file_FrsPageReqIdl4lp_proto_rawDesc = "" +
	"\n" +
	"\x16FrsPageReqIdl4lp.proto\x1a\x0fCommonReq.proto\"\x82\x02\n" +
	"\x10FrsPageReqIdl4lp\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.FrsPageReqIdl4lp.DataReqR\x04data\x1a\xbe\x01\n" +
	"\aDataReq\x12\"\n" +
	"\x06common\x18' \x01(\v2\n" +
	".CommonReqR\x06common\x12\x0e\n" +
	"\x02kw\x18\x01 \x01(\tR\x02kw\x12\x0e\n" +
	"\x02rn\x18\x02 \x01(\x05R\x02rn\x12\x17\n" +
	"\arn_need\x18\x03 \x01(\x05R\x06rnNeed\x12\x17\n" +
	"\ais_good\x18\x04 \x01(\x05R\x06isGood\x12\x10\n" +
	"\x03cid\x18\x05 \x01(\x05R\x03cid\x12\x0e\n" +
	"\x02pn\x18\x0f \x01(\x05R\x02pn\x12\x1b\n" +
	"\tsort_type\x18/ \x01(\x05R\bsortTypeb\x06proto3"

var (
	file_FrsPageReqIdl4lp_proto_rawDescOnce sync.Once
	file_FrsPageReqIdl4lp_proto_rawDescData []byte
)

func file_FrsPageReqIdl4lp_proto_rawDescGZIP() []byte {
	file_FrsPageReqIdl4lp_proto_rawDescOnce.Do(func() {
		file_FrsPageReqIdl4lp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FrsPageReqIdl4lp_proto_rawDesc), len(file_FrsPageReqIdl4lp_proto_rawDesc)))
	})
	return file_FrsPageReqIdl4lp_proto_rawDescData
}

var file_FrsPageReqIdl4lp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_FrsPageReqIdl4lp_proto_goTypes = []any{
	(*FrsPageReqIdl4Lp)(nil),         // 0: FrsPageReqIdl4lp
	(*FrsPageReqIdl4Lp_DataReq)(nil), // 1: FrsPageReqIdl4lp.DataReq
	(*protobuf.CommonReq)(nil),       // 2: CommonReq
}
var file_FrsPageReqIdl4lp_proto_depIdxs = []int32{
	1, // 0: FrsPageReqIdl4lp.data:type_name -> FrsPageReqIdl4lp.DataReq
	2, // 1: FrsPageReqIdl4lp.DataReq.common:type_name -> CommonReq
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_FrsPageReqIdl4lp_proto_init() }
func file_FrsPageReqIdl4lp_proto_init() {
	if File_FrsPageReqIdl4lp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FrsPageReqIdl4lp_proto_rawDesc), len(file_FrsPageReqIdl4lp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FrsPageReqIdl4lp_proto_goTypes,
		DependencyIndexes: file_FrsPageReqIdl4lp_proto_depIdxs,
		MessageInfos:      file_FrsPageReqIdl4lp_proto_msgTypes,
	}.Build()
	File_FrsPageReqIdl4lp_proto = out.File
	file_FrsPageReqIdl4lp_proto_goTypes = nil
	file_FrsPageReqIdl4lp_proto_depIdxs = nil
}
