// tbclient.FrsPage.FrsPageResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: FrsPageResIdl4lp.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrsPageResIdl4Lp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Error         *protobuf.Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *FrsPageResIdl4Lp_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl4Lp) Reset() {
	*x = FrsPageResIdl4Lp{}
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl4Lp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl4Lp) ProtoMessage() {}

func (x *FrsPageResIdl4Lp) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl4Lp.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl4Lp) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl4lp_proto_rawDescGZIP(), []int{0}
}

func (x *FrsPageResIdl4Lp) GetError() *protobuf.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FrsPageResIdl4Lp) GetData() *FrsPageResIdl4Lp_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type FrsPageResIdl4Lp_DataRes struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Forum         *FrsPageResIdl4Lp_DataRes_ForumInfo `protobuf:"bytes,2,opt,name=forum,proto3" json:"forum,omitempty"`
	Page          *protobuf.Page                      `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	ThreadList    []*protobuf.ThreadInfo              `protobuf:"bytes,7,rep,name=thread_list,json=threadList,proto3" json:"thread_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl4Lp_DataRes) Reset() {
	*x = FrsPageResIdl4Lp_DataRes{}
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl4Lp_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl4Lp_DataRes) ProtoMessage() {}

func (x *FrsPageResIdl4Lp_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl4Lp_DataRes.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl4Lp_DataRes) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl4lp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FrsPageResIdl4Lp_DataRes) GetForum() *FrsPageResIdl4Lp_DataRes_ForumInfo {
	if x != nil {
		return x.Forum
	}
	return nil
}

func (x *FrsPageResIdl4Lp_DataRes) GetPage() *protobuf.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *FrsPageResIdl4Lp_DataRes) GetThreadList() []*protobuf.ThreadInfo {
	if x != nil {
		return x.ThreadList
	}
	return nil
}

type FrsPageResIdl4Lp_DataRes_ForumInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl4Lp_DataRes_ForumInfo) Reset() {
	*x = FrsPageResIdl4Lp_DataRes_ForumInfo{}
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl4Lp_DataRes_ForumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl4Lp_DataRes_ForumInfo) ProtoMessage() {}

func (x *FrsPageResIdl4Lp_DataRes_ForumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl4lp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl4Lp_DataRes_ForumInfo.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl4Lp_DataRes_ForumInfo) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl4lp_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *FrsPageResIdl4Lp_DataRes_ForumInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FrsPageResIdl4Lp_DataRes_ForumInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_FrsPageResIdl4lp_proto protoreflect.FileDescriptor

const file_FrsPageResIdl4lp_proto_rawDesc = "" +
	"\n" +
	"\x16FrsPageResIdl4lp.proto\x1a\vError.proto\x1a\n" +
	"Page.proto\x1a\x10ThreadInfo.proto\"\xa0\x02\n" +
	"\x10FrsPageResIdl4lp\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x19.FrsPageResIdl4lp.DataResR\x04data\x1a\xbe\x01\n" +
	"\aDataRes\x129\n" +
	"\x05forum\x18\x02 \x01(\v2#.FrsPageResIdl4lp.DataRes.ForumInfoR\x05forum\x12\x19\n" +
	"\x04page\x18\x04 \x01(\v2\x05.PageR\x04page\x12,\n" +
	"\vthread_list\x18\a \x03(\v2\v.ThreadInfoR\n" +
	"threadList\x1a/\n" +
	"\tForumInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameb\x06proto3"

var (
	file_FrsPageResIdl4lp_proto_rawDescOnce sync.Once
	file_FrsPageResIdl4lp_proto_rawDescData []byte
)

func file_FrsPageResIdl4lp_proto_rawDescGZIP() []byte {
	file_FrsPageResIdl4lp_proto_rawDescOnce.Do(func() {
		file_FrsPageResIdl4lp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FrsPageResIdl4lp_proto_rawDesc), len(file_FrsPageResIdl4lp_proto_rawDesc)))
	})
	return file_FrsPageResIdl4lp_proto_rawDescData
}

var file_FrsPageResIdl4lp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_FrsPageResIdl4lp_proto_goTypes = []any{
	(*FrsPageResIdl4Lp)(nil),                   // 0: FrsPageResIdl4lp
	(*FrsPageResIdl4Lp_DataRes)(nil),           // 1: FrsPageResIdl4lp.DataRes
	(*FrsPageResIdl4Lp_DataRes_ForumInfo)(nil), // 2: FrsPageResIdl4lp.DataRes.ForumInfo
	(*protobuf.Error)(nil),                     // 3: Error
	(*protobuf.Page)(nil),                      // 4: Page
	(*protobuf.ThreadInfo)(nil),                // 5: ThreadInfo
}
var file_FrsPageResIdl4lp_proto_depIdxs = []int32{
	3, // 0: FrsPageResIdl4lp.error:type_name -> Error
	1, // 1: FrsPageResIdl4lp.data:type_name -> FrsPageResIdl4lp.DataRes
	2, // 2: FrsPageResIdl4lp.DataRes.forum:type_name -> FrsPageResIdl4lp.DataRes.ForumInfo
	4, // 3: FrsPageResIdl4lp.DataRes.page:type_name -> Page
	5, // 4: FrsPageResIdl4lp.DataRes.thread_list:type_name -> ThreadInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_FrsPageResIdl4lp_proto_init() }
func file_FrsPageResIdl4lp_proto_init() {
	if File_FrsPageResIdl4lp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FrsPageResIdl4lp_proto_rawDesc), len(file_FrsPageResIdl4lp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FrsPageResIdl4lp_proto_goTypes,
		DependencyIndexes: file_FrsPageResIdl4lp_proto_depIdxs,
		MessageInfos:      file_FrsPageResIdl4lp_proto_msgTypes,
	}.Build()
	File_FrsPageResIdl4lp_proto = out.File
	file_FrsPageResIdl4lp_proto_goTypes = nil
	file_FrsPageResIdl4lp_proto_depIdxs = nil
}
