// tbclient.FrsPage.FrsPageResIdl

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: FrsPageResIdl.proto

package protobuf

import (
	protobuf "github.com/rongyuio/aiotieba-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	FeedList      []*PageData_LayoutFactory `protobuf:"bytes,2,rep,name=feed_list,json=feedList,proto3" json:"feed_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData) Reset() {
	*x = PageData{}
	mi := &file_FrsPageResIdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData) ProtoMessage() {}

func (x *PageData) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData.ProtoReflect.Descriptor instead.
func (*PageData) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0}
}

func (x *PageData) GetFeedList() []*PageData_LayoutFactory {
	if x != nil {
		return x.FeedList
	}
	return nil
}

type FrsPageResIdl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *protobuf.Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          *FrsPageResIdl_DataRes `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl) Reset() {
	*x = FrsPageResIdl{}
	mi := &file_FrsPageResIdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl) ProtoMessage() {}

func (x *FrsPageResIdl) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1}
}

func (x *FrsPageResIdl) GetError() *protobuf.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FrsPageResIdl) GetData() *FrsPageResIdl_DataRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type PageData_LayoutFactory struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Layout        string                             `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Feed          *PageData_LayoutFactory_FeedLayout `protobuf:"bytes,2,opt,name=feed,proto3" json:"feed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory) Reset() {
	*x = PageData_LayoutFactory{}
	mi := &file_FrsPageResIdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory) ProtoMessage() {}

func (x *PageData_LayoutFactory) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PageData_LayoutFactory) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *PageData_LayoutFactory) GetFeed() *PageData_LayoutFactory_FeedLayout {
	if x != nil {
		return x.Feed
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout struct {
	state         protoimpl.MessageState                                `protogen:"open.v1"`
	Components    []*PageData_LayoutFactory_FeedLayout_ComponentFactory `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	BusinessInfo  []*PageData_LayoutFactory_FeedLayout_FeedKV           `protobuf:"bytes,5,rep,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout) Reset() {
	*x = PageData_LayoutFactory_FeedLayout{}
	mi := &file_FrsPageResIdl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PageData_LayoutFactory_FeedLayout) GetComponents() []*PageData_LayoutFactory_FeedLayout_ComponentFactory {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *PageData_LayoutFactory_FeedLayout) GetBusinessInfo() []*PageData_LayoutFactory_FeedLayout_FeedKV {
	if x != nil {
		return x.BusinessInfo
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory struct {
	state         protoimpl.MessageState                                                `protogen:"open.v1"`
	Component     string                                                                `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	FeedTitle     *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent    `protobuf:"bytes,3,opt,name=feed_title,json=feedTitle,proto3" json:"feed_title,omitempty"`
	FeedAbstract  *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent `protobuf:"bytes,4,opt,name=feed_abstract,json=feedAbstract,proto3" json:"feed_abstract,omitempty"`
	FeedPic       *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent  `protobuf:"bytes,7,opt,name=feed_pic,json=feedPic,proto3" json:"feed_pic,omitempty"`
	FeedPoll      *protobuf.PollInfo                                                    `protobuf:"bytes,22,opt,name=feed_poll,json=feedPoll,proto3" json:"feed_poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory{}
	mi := &file_FrsPageResIdl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) GetFeedTitle() *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent {
	if x != nil {
		return x.FeedTitle
	}
	return nil
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) GetFeedAbstract() *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent {
	if x != nil {
		return x.FeedAbstract
	}
	return nil
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) GetFeedPic() *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent {
	if x != nil {
		return x.FeedPic
	}
	return nil
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory) GetFeedPoll() *protobuf.PollInfo {
	if x != nil {
		return x.FeedPoll
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_FeedKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_FeedKV) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_FeedKV{}
	mi := &file_FrsPageResIdl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_FeedKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_FeedKV) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_FeedKV) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_FeedKV.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_FeedKV) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *PageData_LayoutFactory_FeedLayout_FeedKV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_FeedKV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource struct {
	state         protoimpl.MessageState                                                                   `protogen:"open.v1"`
	Type          int32                                                                                    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	TextInfo      *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText  `protobuf:"bytes,8,opt,name=text_info,json=textInfo,proto3" json:"text_info,omitempty"`
	EmojiInfo     *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji `protobuf:"bytes,10,opt,name=emoji_info,json=emojiInfo,proto3" json:"emoji_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource{}
	mi := &file_FrsPageResIdl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) GetTextInfo() *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText {
	if x != nil {
		return x.TextInfo
	}
	return nil
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource) GetEmojiInfo() *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji {
	if x != nil {
		return x.EmojiInfo
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmallPicUrl   string                 `protobuf:"bytes,1,opt,name=small_pic_url,json=smallPicUrl,proto3" json:"small_pic_url,omitempty"`
	BigPicUrl     string                 `protobuf:"bytes,2,opt,name=big_pic_url,json=bigPicUrl,proto3" json:"big_pic_url,omitempty"`
	OriginPicUrl  string                 `protobuf:"bytes,3,opt,name=origin_pic_url,json=originPicUrl,proto3" json:"origin_pic_url,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo{}
	mi := &file_FrsPageResIdl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 1}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) GetSmallPicUrl() string {
	if x != nil {
		return x.SmallPicUrl
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) GetBigPicUrl() string {
	if x != nil {
		return x.BigPicUrl
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) GetOriginPicUrl() string {
	if x != nil {
		return x.OriginPicUrl
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent struct {
	state         protoimpl.MessageState                                                    `protogen:"open.v1"`
	Data          []*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent{}
	mi := &file_FrsPageResIdl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 2}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent) GetData() []*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent struct {
	state         protoimpl.MessageState                                                    `protogen:"open.v1"`
	Data          []*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent{}
	mi := &file_FrsPageResIdl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 3}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent) GetData() []*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent struct {
	state         protoimpl.MessageState                                        `protogen:"open.v1"`
	Pics          []*PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo `protobuf:"bytes,1,rep,name=pics,proto3" json:"pics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent{}
	mi := &file_FrsPageResIdl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) ProtoMessage() {}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent) GetPics() []*PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo {
	if x != nil {
		return x.Pics
	}
	return nil
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText{}
	mi := &file_FrsPageResIdl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) ProtoMessage() {
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	C             string                 `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) Reset() {
	*x = PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji{}
	mi := &file_FrsPageResIdl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) ProtoMessage() {
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji.ProtoReflect.Descriptor instead.
func (*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 1}
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type FrsPageResIdl_DataRes struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Forum         *FrsPageResIdl_DataRes_ForumInfo       `protobuf:"bytes,2,opt,name=forum,proto3" json:"forum,omitempty"`
	Page          *protobuf.Page                         `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	ThreadList    []*protobuf.ThreadInfo                 `protobuf:"bytes,7,rep,name=thread_list,json=threadList,proto3" json:"thread_list,omitempty"`
	UserList      []*protobuf.User                       `protobuf:"bytes,17,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	NavTabInfo    *FrsPageResIdl_DataRes_NavTabInfo      `protobuf:"bytes,37,opt,name=nav_tab_info,json=navTabInfo,proto3" json:"nav_tab_info,omitempty"`
	ForumRule     *FrsPageResIdl_DataRes_ForumRuleStatus `protobuf:"bytes,105,opt,name=forum_rule,json=forumRule,proto3" json:"forum_rule,omitempty"`
	PageData      *PageData                              `protobuf:"bytes,126,opt,name=page_data,json=pageData,proto3" json:"page_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl_DataRes) Reset() {
	*x = FrsPageResIdl_DataRes{}
	mi := &file_FrsPageResIdl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl_DataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl_DataRes) ProtoMessage() {}

func (x *FrsPageResIdl_DataRes) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl_DataRes.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl_DataRes) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FrsPageResIdl_DataRes) GetForum() *FrsPageResIdl_DataRes_ForumInfo {
	if x != nil {
		return x.Forum
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetPage() *protobuf.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetThreadList() []*protobuf.ThreadInfo {
	if x != nil {
		return x.ThreadList
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetUserList() []*protobuf.User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetNavTabInfo() *FrsPageResIdl_DataRes_NavTabInfo {
	if x != nil {
		return x.NavTabInfo
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetForumRule() *FrsPageResIdl_DataRes_ForumRuleStatus {
	if x != nil {
		return x.ForumRule
	}
	return nil
}

func (x *FrsPageResIdl_DataRes) GetPageData() *PageData {
	if x != nil {
		return x.PageData
	}
	return nil
}

type FrsPageResIdl_DataRes_ForumInfo struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Id            int64                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirstClass    string                                     `protobuf:"bytes,3,opt,name=first_class,json=firstClass,proto3" json:"first_class,omitempty"`
	SecondClass   string                                     `protobuf:"bytes,4,opt,name=second_class,json=secondClass,proto3" json:"second_class,omitempty"`
	MemberNum     int32                                      `protobuf:"varint,9,opt,name=member_num,json=memberNum,proto3" json:"member_num,omitempty"`
	ThreadNum     int32                                      `protobuf:"varint,10,opt,name=thread_num,json=threadNum,proto3" json:"thread_num,omitempty"`
	PostNum       int32                                      `protobuf:"varint,11,opt,name=post_num,json=postNum,proto3" json:"post_num,omitempty"`
	Managers      []*FrsPageResIdl_DataRes_ForumInfo_Manager `protobuf:"bytes,17,rep,name=managers,proto3" json:"managers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl_DataRes_ForumInfo) Reset() {
	*x = FrsPageResIdl_DataRes_ForumInfo{}
	mi := &file_FrsPageResIdl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl_DataRes_ForumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl_DataRes_ForumInfo) ProtoMessage() {}

func (x *FrsPageResIdl_DataRes_ForumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl_DataRes_ForumInfo.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl_DataRes_ForumInfo) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetFirstClass() string {
	if x != nil {
		return x.FirstClass
	}
	return ""
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetSecondClass() string {
	if x != nil {
		return x.SecondClass
	}
	return ""
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetMemberNum() int32 {
	if x != nil {
		return x.MemberNum
	}
	return 0
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetThreadNum() int32 {
	if x != nil {
		return x.ThreadNum
	}
	return 0
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetPostNum() int32 {
	if x != nil {
		return x.PostNum
	}
	return 0
}

func (x *FrsPageResIdl_DataRes_ForumInfo) GetManagers() []*FrsPageResIdl_DataRes_ForumInfo_Manager {
	if x != nil {
		return x.Managers
	}
	return nil
}

type FrsPageResIdl_DataRes_NavTabInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tab           []*protobuf.FrsTabInfo `protobuf:"bytes,1,rep,name=tab,proto3" json:"tab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl_DataRes_NavTabInfo) Reset() {
	*x = FrsPageResIdl_DataRes_NavTabInfo{}
	mi := &file_FrsPageResIdl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl_DataRes_NavTabInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl_DataRes_NavTabInfo) ProtoMessage() {}

func (x *FrsPageResIdl_DataRes_NavTabInfo) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl_DataRes_NavTabInfo.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl_DataRes_NavTabInfo) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *FrsPageResIdl_DataRes_NavTabInfo) GetTab() []*protobuf.FrsTabInfo {
	if x != nil {
		return x.Tab
	}
	return nil
}

type FrsPageResIdl_DataRes_ForumRuleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasForumRule  int32                  `protobuf:"varint,4,opt,name=has_forum_rule,json=hasForumRule,proto3" json:"has_forum_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl_DataRes_ForumRuleStatus) Reset() {
	*x = FrsPageResIdl_DataRes_ForumRuleStatus{}
	mi := &file_FrsPageResIdl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl_DataRes_ForumRuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl_DataRes_ForumRuleStatus) ProtoMessage() {}

func (x *FrsPageResIdl_DataRes_ForumRuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl_DataRes_ForumRuleStatus.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl_DataRes_ForumRuleStatus) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *FrsPageResIdl_DataRes_ForumRuleStatus) GetHasForumRule() int32 {
	if x != nil {
		return x.HasForumRule
	}
	return 0
}

type FrsPageResIdl_DataRes_ForumInfo_Manager struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrsPageResIdl_DataRes_ForumInfo_Manager) Reset() {
	*x = FrsPageResIdl_DataRes_ForumInfo_Manager{}
	mi := &file_FrsPageResIdl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrsPageResIdl_DataRes_ForumInfo_Manager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrsPageResIdl_DataRes_ForumInfo_Manager) ProtoMessage() {}

func (x *FrsPageResIdl_DataRes_ForumInfo_Manager) ProtoReflect() protoreflect.Message {
	mi := &file_FrsPageResIdl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrsPageResIdl_DataRes_ForumInfo_Manager.ProtoReflect.Descriptor instead.
func (*FrsPageResIdl_DataRes_ForumInfo_Manager) Descriptor() ([]byte, []int) {
	return file_FrsPageResIdl_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

var File_FrsPageResIdl_proto protoreflect.FileDescriptor

const file_FrsPageResIdl_proto_rawDesc = "" +
	"\n" +
	"\x13FrsPageResIdl.proto\x1a\vError.proto\x1a\n" +
	"Page.proto\x1a\x10ThreadInfo.proto\x1a\n" +
	"User.proto\x1a\x10FrsTabInfo.proto\x1a\x0ePollInfo.proto\"\xf5\f\n" +
	"\bPageData\x124\n" +
	"\tfeed_list\x18\x02 \x03(\v2\x17.PageData.LayoutFactoryR\bfeedList\x1a\xb2\f\n" +
	"\rLayoutFactory\x12\x16\n" +
	"\x06layout\x18\x01 \x01(\tR\x06layout\x126\n" +
	"\x04feed\x18\x02 \x01(\v2\".PageData.LayoutFactory.FeedLayoutR\x04feed\x1a\xd0\v\n" +
	"\n" +
	"FeedLayout\x12S\n" +
	"\n" +
	"components\x18\x01 \x03(\v23.PageData.LayoutFactory.FeedLayout.ComponentFactoryR\n" +
	"components\x12N\n" +
	"\rbusiness_info\x18\x05 \x03(\v2).PageData.LayoutFactory.FeedLayout.FeedKVR\fbusinessInfo\x1a\xea\t\n" +
	"\x10ComponentFactory\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12a\n" +
	"\n" +
	"feed_title\x18\x03 \x01(\v2B.PageData.LayoutFactory.FeedLayout.ComponentFactory.TitleComponentR\tfeedTitle\x12j\n" +
	"\rfeed_abstract\x18\x04 \x01(\v2E.PageData.LayoutFactory.FeedLayout.ComponentFactory.AbstractComponentR\ffeedAbstract\x12_\n" +
	"\bfeed_pic\x18\a \x01(\v2D.PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedPicComponentR\afeedPic\x12&\n" +
	"\tfeed_poll\x18\x16 \x01(\v2\t.PollInfoR\bfeedPoll\x1a\xf5\x02\n" +
	"\x13FeedContentResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12t\n" +
	"\ttext_info\x18\b \x01(\v2W.PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentTextR\btextInfo\x12w\n" +
	"\n" +
	"emoji_info\x18\n" +
	" \x01(\v2X.PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentEmojiR\temojiInfo\x1a%\n" +
	"\x0fFeedContentText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a4\n" +
	"\x10FeedContentEmoji\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\f\n" +
	"\x01c\x18\x02 \x01(\tR\x01c\x1a\xa1\x01\n" +
	"\aPicInfo\x12\"\n" +
	"\rsmall_pic_url\x18\x01 \x01(\tR\vsmallPicUrl\x12\x1e\n" +
	"\vbig_pic_url\x18\x02 \x01(\tR\tbigPicUrl\x12$\n" +
	"\x0eorigin_pic_url\x18\x03 \x01(\tR\foriginPicUrl\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x1am\n" +
	"\x0eTitleComponent\x12[\n" +
	"\x04data\x18\x01 \x03(\v2G.PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResourceR\x04data\x1ap\n" +
	"\x11AbstractComponent\x12[\n" +
	"\x04data\x18\x01 \x03(\v2G.PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResourceR\x04data\x1ac\n" +
	"\x10FeedPicComponent\x12O\n" +
	"\x04pics\x18\x01 \x03(\v2;.PageData.LayoutFactory.FeedLayout.ComponentFactory.PicInfoR\x04pics\x1a0\n" +
	"\x06FeedKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc4\x06\n" +
	"\rFrsPageResIdl\x12\x1c\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorR\x05error\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.FrsPageResIdl.DataResR\x04data\x1a\xe8\x05\n" +
	"\aDataRes\x126\n" +
	"\x05forum\x18\x02 \x01(\v2 .FrsPageResIdl.DataRes.ForumInfoR\x05forum\x12\x19\n" +
	"\x04page\x18\x04 \x01(\v2\x05.PageR\x04page\x12,\n" +
	"\vthread_list\x18\a \x03(\v2\v.ThreadInfoR\n" +
	"threadList\x12\"\n" +
	"\tuser_list\x18\x11 \x03(\v2\x05.UserR\buserList\x12C\n" +
	"\fnav_tab_info\x18% \x01(\v2!.FrsPageResIdl.DataRes.NavTabInfoR\n" +
	"navTabInfo\x12E\n" +
	"\n" +
	"forum_rule\x18i \x01(\v2&.FrsPageResIdl.DataRes.ForumRuleStatusR\tforumRule\x12&\n" +
	"\tpage_data\x18~ \x01(\v2\t.PageDataR\bpageData\x1a\x9d\x02\n" +
	"\tForumInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfirst_class\x18\x03 \x01(\tR\n" +
	"firstClass\x12!\n" +
	"\fsecond_class\x18\x04 \x01(\tR\vsecondClass\x12\x1d\n" +
	"\n" +
	"member_num\x18\t \x01(\x05R\tmemberNum\x12\x1d\n" +
	"\n" +
	"thread_num\x18\n" +
	" \x01(\x05R\tthreadNum\x12\x19\n" +
	"\bpost_num\x18\v \x01(\x05R\apostNum\x12D\n" +
	"\bmanagers\x18\x11 \x03(\v2(.FrsPageResIdl.DataRes.ForumInfo.ManagerR\bmanagers\x1a\t\n" +
	"\aManager\x1a+\n" +
	"\n" +
	"NavTabInfo\x12\x1d\n" +
	"\x03tab\x18\x01 \x03(\v2\v.FrsTabInfoR\x03tab\x1a7\n" +
	"\x0fForumRuleStatus\x12$\n" +
	"\x0ehas_forum_rule\x18\x04 \x01(\x05R\fhasForumRuleb\x06proto3"

var (
	file_FrsPageResIdl_proto_rawDescOnce sync.Once
	file_FrsPageResIdl_proto_rawDescData []byte
)

func file_FrsPageResIdl_proto_rawDescGZIP() []byte {
	file_FrsPageResIdl_proto_rawDescOnce.Do(func() {
		file_FrsPageResIdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FrsPageResIdl_proto_rawDesc), len(file_FrsPageResIdl_proto_rawDesc)))
	})
	return file_FrsPageResIdl_proto_rawDescData
}

var file_FrsPageResIdl_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_FrsPageResIdl_proto_goTypes = []any{
	(*PageData)(nil),                                                                                // 0: PageData
	(*FrsPageResIdl)(nil),                                                                           // 1: FrsPageResIdl
	(*PageData_LayoutFactory)(nil),                                                                  // 2: PageData.LayoutFactory
	(*PageData_LayoutFactory_FeedLayout)(nil),                                                       // 3: PageData.LayoutFactory.FeedLayout
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory)(nil),                                      // 4: PageData.LayoutFactory.FeedLayout.ComponentFactory
	(*PageData_LayoutFactory_FeedLayout_FeedKV)(nil),                                                // 5: PageData.LayoutFactory.FeedLayout.FeedKV
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource)(nil),                  // 6: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_PicInfo)(nil),                              // 7: PageData.LayoutFactory.FeedLayout.ComponentFactory.PicInfo
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_TitleComponent)(nil),                       // 8: PageData.LayoutFactory.FeedLayout.ComponentFactory.TitleComponent
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_AbstractComponent)(nil),                    // 9: PageData.LayoutFactory.FeedLayout.ComponentFactory.AbstractComponent
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedPicComponent)(nil),                     // 10: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedPicComponent
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentText)(nil),  // 11: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentText
	(*PageData_LayoutFactory_FeedLayout_ComponentFactory_FeedContentResource_FeedContentEmoji)(nil), // 12: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentEmoji
	(*FrsPageResIdl_DataRes)(nil),                                                                   // 13: FrsPageResIdl.DataRes
	(*FrsPageResIdl_DataRes_ForumInfo)(nil),                                                         // 14: FrsPageResIdl.DataRes.ForumInfo
	(*FrsPageResIdl_DataRes_NavTabInfo)(nil),                                                        // 15: FrsPageResIdl.DataRes.NavTabInfo
	(*FrsPageResIdl_DataRes_ForumRuleStatus)(nil),                                                   // 16: FrsPageResIdl.DataRes.ForumRuleStatus
	(*FrsPageResIdl_DataRes_ForumInfo_Manager)(nil),                                                 // 17: FrsPageResIdl.DataRes.ForumInfo.Manager
	(*protobuf.Error)(nil),                                                                          // 18: Error
	(*protobuf.PollInfo)(nil),                                                                       // 19: PollInfo
	(*protobuf.Page)(nil),                                                                           // 20: Page
	(*protobuf.ThreadInfo)(nil),                                                                     // 21: ThreadInfo
	(*protobuf.User)(nil),                                                                           // 22: User
	(*protobuf.FrsTabInfo)(nil),                                                                     // 23: FrsTabInfo
}
var file_FrsPageResIdl_proto_depIdxs = []int32{
	2,  // 0: PageData.feed_list:type_name -> PageData.LayoutFactory
	18, // 1: FrsPageResIdl.error:type_name -> Error
	13, // 2: FrsPageResIdl.data:type_name -> FrsPageResIdl.DataRes
	3,  // 3: PageData.LayoutFactory.feed:type_name -> PageData.LayoutFactory.FeedLayout
	4,  // 4: PageData.LayoutFactory.FeedLayout.components:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory
	5,  // 5: PageData.LayoutFactory.FeedLayout.business_info:type_name -> PageData.LayoutFactory.FeedLayout.FeedKV
	8,  // 6: PageData.LayoutFactory.FeedLayout.ComponentFactory.feed_title:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.TitleComponent
	9,  // 7: PageData.LayoutFactory.FeedLayout.ComponentFactory.feed_abstract:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.AbstractComponent
	10, // 8: PageData.LayoutFactory.FeedLayout.ComponentFactory.feed_pic:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedPicComponent
	19, // 9: PageData.LayoutFactory.FeedLayout.ComponentFactory.feed_poll:type_name -> PollInfo
	11, // 10: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.text_info:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentText
	12, // 11: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.emoji_info:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource.FeedContentEmoji
	6,  // 12: PageData.LayoutFactory.FeedLayout.ComponentFactory.TitleComponent.data:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource
	6,  // 13: PageData.LayoutFactory.FeedLayout.ComponentFactory.AbstractComponent.data:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedContentResource
	7,  // 14: PageData.LayoutFactory.FeedLayout.ComponentFactory.FeedPicComponent.pics:type_name -> PageData.LayoutFactory.FeedLayout.ComponentFactory.PicInfo
	14, // 15: FrsPageResIdl.DataRes.forum:type_name -> FrsPageResIdl.DataRes.ForumInfo
	20, // 16: FrsPageResIdl.DataRes.page:type_name -> Page
	21, // 17: FrsPageResIdl.DataRes.thread_list:type_name -> ThreadInfo
	22, // 18: FrsPageResIdl.DataRes.user_list:type_name -> User
	15, // 19: FrsPageResIdl.DataRes.nav_tab_info:type_name -> FrsPageResIdl.DataRes.NavTabInfo
	16, // 20: FrsPageResIdl.DataRes.forum_rule:type_name -> FrsPageResIdl.DataRes.ForumRuleStatus
	0,  // 21: FrsPageResIdl.DataRes.page_data:type_name -> PageData
	17, // 22: FrsPageResIdl.DataRes.ForumInfo.managers:type_name -> FrsPageResIdl.DataRes.ForumInfo.Manager
	23, // 23: FrsPageResIdl.DataRes.NavTabInfo.tab:type_name -> FrsTabInfo
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_FrsPageResIdl_proto_init() }
func file_FrsPageResIdl_proto_init() {
	if File_FrsPageResIdl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FrsPageResIdl_proto_rawDesc), len(file_FrsPageResIdl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FrsPageResIdl_proto_goTypes,
		DependencyIndexes: file_FrsPageResIdl_proto_depIdxs,
		MessageInfos:      file_FrsPageResIdl_proto_msgTypes,
	}.Build()
	File_FrsPageResIdl_proto = out.File
	file_FrsPageResIdl_proto_goTypes = nil
	file_FrsPageResIdl_proto_depIdxs = nil
}
